services:
  gi_stat_app:
    container_name: "gi-stat-app"
    build:
      context: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
    env_file:
      - .env
    command: ["python manage.py runserver 0.0.0.0:8000"]
