[tool.black]
line-length = 120
target-version = ['py39']
include = '\.py$'
force-exclude = '''
/(
    \.eggs
  | \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | build
  | dist
  | lib
  | include
  | bin
  | vendor
)/
'''
