# Generated by Django 4.1.4 on 2025-11-27 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField(unique=True)),
                ("release_date", models.DateTimeField()),
                (
                    "talent_days",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Всегда"),
                            (1, "Понедельник/Четверг"),
                            (2, "Вторник/Пятница"),
                            (3, "Среда/Суббота"),
                        ]
                    ),
                ),
                ("talent_domain", models.TextField()),
                ("weekly_boss", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chat_id", models.BigIntegerField(unique=True)),
                ("is_subscribed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="UserCharacter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("normal_attack", models.PositiveSmallIntegerField(default=0)),
                ("elemental_skill", models.PositiveSmallIntegerField(default=0)),
                ("elemental_burst", models.PositiveSmallIntegerField(default=0)),
                ("character", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tg_bot.character")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tg_bot.user")),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="characters",
            field=models.ManyToManyField(related_name="users", through="tg_bot.UserCharacter", to="tg_bot.character"),
        ),
    ]
