# Generated by Django 4.1.4 on 2023-01-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tg_bot", "0002_user_is_subscribed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="character",
            options={"ordering": ["-release_date"]},
        ),
        migrations.AddField(
            model_name="character",
            name="release_date",
            field=models.DateTimeField(null=True),
        ),
    ]
