name: Django application

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_NAME: "github_ci"
      DB_USER: "root"
      DB_PASSWORD: "password"
      DB_HOST: "127.0.0.1"
      DB_PORT: "3306"
      SECRET_KEY: "test-secret-key"

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: github_ci
        ports: [ '3306:3306' ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run migrations
      run: |
        python manage.py migrate
    - name: Run tests
      run: |
        coverage run manage.py test
    - name: Run coverage report
      run: |
        coverage report --fail-under=70
